n = input('digite algo: ')
print('o tipo primitivo', type(n))
print('espaços?', n.isspace())
print('numeros?', n.isnumeric())
print('alfabetico?', n.isalpha())
print('alpha numerico?', n.isalnum())
print('maisculas?', n.isupper())
print('minusculas?', n.islower())
print('capitalizada?', n.istitle())